name: CI/CD Deploy

on:
  push:
    branches:
      - master
      - dev

jobs:
  ci:
    name: CI (Build & Check)
    runs-on: ubuntu-latest   # 🔥 dev tidak pakai server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Optional (kalau nanti ada test)
      # - name: Run tests
      #   run: pytest


  deploy:
    name: Deploy to Server
    needs: ci
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
            cd /home/thanel/skripsi/skripsi-backend

            echo "Pull latest code..."
            git pull origin main

            echo "Activate virtualenv..."
            source venv/bin/activate

            echo "Upgrade pip..."
            pip install --upgrade pip

            echo "Install dependencies..."
            pip install -r requirements.txt

            echo "Restart service..."
            sudo systemctl restart attack-detect

            echo "Deploy selesai ✅"